### ISSUE TITLE
讨论

### ISSUE THREAD

**Issue by Kedreamix** [Dreaming-future/Pytorch-Image-Classification#1]
有什么问题都可以在这里讨论，我都会看并且一一解答的哦

**Comment by myfeet2cold** [comment]
您好，输入图片的尺寸是32*32，但是有些网络结构的输入是大于32*32的，请问是直接把图片尺寸拉伸然后输入么？

**Comment by Kedreamix** [comment]
> 您好，输入图片的尺寸是32*32，但是有些网络结构的输入是大于32*32的，请问是直接把图片尺寸拉伸然后输入么？

可以进行拉伸，这是可以的，但是会减少图片分辨率，得到的信息减少。比如传统的imagenet的图片输入都是256x256x3的图片，有些可以利用平均池化自适应改变最后一层的输入，最后输出结果。

在这一部分，确实是进行拉伸后输入的，但是resnet等有平均池化操作就可以允许其他图片尺寸输入

希望回答对你有帮助

**Comment by myfeet2cold** [comment]
您好，再次向您请教，在您的代码中包含：
`from utils import train
from utils import plot_history`
但我安装了utils包后，仍报错，提示“cannot import name 'train' from 'utils'”

**Comment by de6v56s** [comment]
您好，请问，我用pycharm打开train.py运行后，如何做出学习曲线图呢？加了下面代码也不行，希望楼主解答，谢谢
from utils import train
from utils import plot_history
Acc, Loss, Lr = train(net, trainloader, testloader, epoch, optimizer, criterion, scheduler, save_path, verbose = True)
plot_history(epoch ,Acc, Loss, Lr)

**Comment by Kedreamix** [comment]
plot_history(epoch ,Acc, Loss, Lr)这个其实是画出学习曲线图的，但是可能在pycharm中，需要再加一句，plt.plot()可能才能出现

**Comment by jiwei911023** [comment]
您好， 为什么我运行代码之后得到这个错误呢：
ImportError: cannot import name 'train' from 'utils' (/usr/local/lib/python3.7/dist-packages/utils/__init__.py)
