### ISSUE TITLE
why the code: from utils import train from utils import plot_history   doesn't work?

### ISSUE THREAD

**Issue by jiwei911023** [Dreaming-future/Pytorch-Image-Classification#2]

**Comment by jiwei911023** [comment]
ImportError: cannot import name 'train' from 'utils' (/usr/local/lib/python3.7/dist-packages/utils/__init__.py)

**Comment by Kedreamix** [comment]
你好，那是因为，在我的文件夹下，有一个utils.py的文件，这个文件包含了训练函数，也要加进去的

**Comment by jiwei911023** [comment]
谢谢， 请问您有微信公众号之类的可以通过别的方式联系您吗

**Comment by Kedreamix** [comment]
有的，我的qq为1016617094@qq.com,wx为pikachu2biubiu

**Comment by jiwei911023** [comment]
我加了您刚更新的utlis2的代码但是还是不行呀。 
from utils import train

在那段代码里只定义了train function但是我没看到有utlis的function。 utlis是您自己定义的吗还是pytorch自带的啊

**Comment by Kedreamix** [comment]
不要加util2哈哈，加utils.py，那个我还没写教程呢

**Comment by Kedreamix** [comment]
我自己定义的utils.py

**Comment by jiwei911023** [comment]
加完utils之后还是不行呀。依然得到以下error
ImportError: cannot import name 'train' from 'utils' (/usr/local/lib/python3.7/dist-packages/utils/__init__.py)
